server:
  servlet:
    context-path: /produdoro/api

    springdoc:
      swagger-ui:
        path: /swagger-ui

    spring:
      data:
        mongodb:
          authentication-database: admin
        uri: ${MONGO_DB_URI:mongodb+srv://liwdev23:W945766on@cluster0.peh5zhp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
        auto-index-creation: true






